spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  application:
    name: dotburgas
  datasource:
    url: jdbc:mysql://localhost:3306/dotburgas?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
  profiles:
    active: dev
server:
  port: 8080

logging:
  level:
    org.springframework.web.filter.HiddenHttpMethodFilter: DEBUG
