spring:
  application:
    name: dotburgas
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Use the correct dialect for MySQL 8
      ddl-auto: update  # Automatically update the database schema
      format_sql: true
  security:
    user:
      name: Petar123
      password: 123123
  mail:
    host: smtp.gmail.com
    port: 587
    username: petargmatev@gmail.com
    password: miit cfwt jdeq zwkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/dotburgas?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
  sql:
    init:
      mode: never
  profiles:
    active: dev
server:
  port: 8080
logging:
  level:
    org.hibernate.orm.connections.pooling: warn
    com.zaxxer.hikari: warn
notification-svc:
  failure-message:
    clear-history: Notification service is temporarily down! Please try again later!

